apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  annotations:
    volume.kubernetes.io/storage-provisioner: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: standard
  resources:
    requests:
      storage: 8Gi