apiVersion: v1
kind: Service
metadata:
  name: myapp1-nodeport-service
spec:
  type: NodePort  # ClusterIP, # LoadBalancer
  selector:
    app: myapp1 
  ports:
    - name: http 
      port: 80   # Service port 
      targetPort: 80   # container port
      nodePort: 30001  # Node port
