---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/bastion_setup

    - name: Import VPC setup Variable
      include_vars: vars/outputs_vars

    - name: Create vprofile ec2 key
      ec2_key:
        state: "{{ state }}"
        name: vprofile-key
        region: "{{ region }}"
      register: key_output

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{ key_output.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_output.changed

    - name: Create Sec Grp for bastion host
      ec2_group:
        state: "{{ state }}"
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_output

    - name: Creating Bastion Host
      ec2_instance:
        state: "{{ state }}"
        name: "Bastion-Host"
        key_name: "vprofile-key"
        region: "{{ region }}"
        instance_type: t2.micro
        image_id : "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps Team
        exact_count: 1
        user_data: userdata/script.sh
        security_group: "{{ BastionSG_output.group_id }}"
        vpc_subnet_id: "{{ pubsub1id }}"
      register: bastionHost_output

    - debug:
        var: bastionHost_output.public_ip

