apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  ports:
    - port: 30001
      nodePort: 30001
      targetPort: http-port
      protocol: TCP
  selector:
     app: wordpress
  type: NodePort
